name: Rust

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cargo install count_set_bits
      run: cargo install count_set_bits
    - name: cargo build --verbose
      run: cargo build --verbose
    - name: cargo test --verbose -- --nocapture
      run: cargo test --verbose -- --nocapture

